spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
vault:
  uri: http://localhost:8200
  token: hvs.7fhtvM1hFvBPPAa540Hohq4H
datamart:
  url: AppVaultUrl
  username: AppVaultUsername
  password: AppVaultPassword
